[package]
name = "rust-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
keyring = "3.6.2"
matrix-sdk = "0.13.0"
tokio = {version = "1.46.1", features = ["rt-multi-thread"]}
