[package]
name = "rust-matrix"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.1.0"
crossterm = "0.28.1"
anyhow = "1.0.98"
keyring = "3.6.2"
matrix-sdk = "0.13.0"
tokio = {version = "1.46.1", features = ["rt-multi-thread"]}
whoami = "1.6.0"
serde = "1.0.219"
serde_json = "1.0.140"
